lmtsufape/hvu

back/src/main/java/br/edu/ufape/hvu/controller/AnimalController.java, back/src/main/java/br/edu/ufape/hvu/controller/EspecieController.java, back/src/main/java/br/edu/ufape/hvu/controller/HistoricoMedicoPregressoController.java, back/src/main/java/br/edu/ufape/hvu/controller/MedicacaoPeriodicaController.java, back/src/main/java/br/edu/ufape/hvu/controller/RacaController.java, back/src/main/java/br/edu/ufape/hvu/controller/TutorController.java, back/src/main/java/br/edu/ufape/hvu/exception/IdNotFoundException.java, back/src/main/java/br/edu/ufape/hvu/exception/types/BusinessException.java, back/src/main/java/br/edu/ufape/hvu/exception/types/NotFoundException.java, back/src/main/java/br/edu/ufape/hvu/exception/types/TechnicalException.java, back/src/main/java/br/edu/ufape/hvu/exception/types/global/ErrorResponse.java, back/src/main/java/br/edu/ufape/hvu/exception/types/global/ExceptionCustomized.java, back/src/main/java/br/edu/ufape/hvu/exception/types/global/GlobalExceptionHandling.java, back/src/main/java/br/edu/ufape/hvu/facade/Facade.java, back/src/main/java/br/edu/ufape/hvu/repository/DiretorRepository.java, back/src/main/java/br/edu/ufape/hvu/repository/MedicoRepository.java, back/src/main/java/br/edu/ufape/hvu/service/AnimalService.java, back/src/main/java/br/edu/ufape/hvu/service/DiretorService.java, back/src/main/java/br/edu/ufape/hvu/service/EspecieService.java, back/src/main/java/br/edu/ufape/hvu/service/HistoricoMedicoPregressoService.java, back/src/main/java/br/edu/ufape/hvu/service/MedicacaoPeriodicaService.java, back/src/main/java/br/edu/ufape/hvu/service/MedicoService.java, back/src/main/java/br/edu/ufape/hvu/service/RacaService.java, back/src/main/java/br/edu/ufape/hvu/service/TutorService.java
=> Add exceptions globais e realizando o IdNotFound para as classes referentes ao Cadastro de Animal

front/src/components/AgendarConsulta/index.js, front/src/components/AgendarConsulta/index.module.css, front/src/components/Footer/index.js, front/src/components/Footer/index.module.css
Foi finalizado o design da tela de agendar a consulta com todos os horários de acordo com o figma do dia 07/03, também pensando na responsividade da página. O footer também foi reorganizado pra poder se adequar melhor a responsividade das páginas do sistema.
=> :lipstick: feat: design da tela de agendar consultas(tutor) e footer

back/src/main/java/br/edu/ufape/hvu/controller/dto/request/FichaSolicitacaoServicoRequest.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/response/FichaSolicitacaoServicoResponse.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/response/LaudoMicroscopiaResponse.java, back/src/main/java/br/edu/ufape/hvu/facade/Facade.java, back/src/main/java/br/edu/ufape/hvu/model/FichaSolicitacaoServico.java, back/src/main/java/br/edu/ufape/hvu/model/LaudoMicroscopia.java, back/src/main/java/br/edu/ufape/hvu/model/LaudoNecropsia.java, back/src/main/java/br/edu/ufape/hvu/model/enums/TipoMaterial.java, back/src/main/java/br/edu/ufape/hvu/model/enums/TipoServico.java, front/package-lock.json, front/package.json
- Alterações no tipo de serviço (Ficha Solicitação de Serviço)
- Remoção do Enum TipoMaterial
- Remoção do Enum TipoServico
- Implementação do método de criar os laudos baseado na escolha da ficha de solicitação de serviço
=> Alterações no LAPA

back/src/main/java/br/edu/ufape/hvu/controller/dto/request/FichaSolicitacaoServicoRequest.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/response/FichaSolicitacaoServicoResponse.java, back/src/main/java/br/edu/ufape/hvu/facade/Facade.java, back/src/main/java/br/edu/ufape/hvu/model/FichaSolicitacaoServico.java, back/src/main/java/br/edu/ufape/hvu/model/LaudoMicroscopia.java
> Remoção de informações desnecessárias
> Adição do Tutor na Ficha de Solicitação de Serviço (A busca do animal para a ficha de solicitação de serviço é através do Tutor)
=> Pequena alteração

back/src/main/java/br/edu/ufape/hvu/controller/FichaSolicitacaoServicoController.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/request/FichaSolicitacaoServicoRequest.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/response/FichaSolicitacaoServicoResponse.java, back/src/main/java/br/edu/ufape/hvu/model/FichaSolicitacaoServico.java, back/src/main/java/br/edu/ufape/hvu/model/enums/TipoServico.java
> Implementação do método de geração do código para os serviços (Necropsia, Microscopia e Necropsia com Microscopia)
> Método para resetar os contadores após a passagem de ano
> Adição do Enum para tipo de serviço
> Mudança na relação do tutor com as fichas de serviço (Um tutor pode ter mais de uma ficha de serviço)
=> Alterações e Implementações na Ficha de Solicitação de Serviço

front/pages/lapa/getFichaById/[id].js, front/pages/lapa/updateFicha/[id].js, front/src/components/Lapa/GetFichaByID/index.js, front/src/components/Lapa/GetFichaByID/index.module.css, front/src/components/Lapa/TelaPrincipalLaudos/LaudosEmAndamento/index.js, front/src/components/Lapa/TelaPrincipalLaudos/LaudosEmAndamento/index.module.css, front/src/components/Lapa/TelaPrincipalLaudos/NovosLaudos/index.js, front/src/components/Lapa/UpdateFicha/index.js, front/src/components/Lapa/UpdateFicha/index.module.css
- Ajuste no componente "Novos Laudos": Tela funcionando corretamente.
- Ajuste no componente "Laudos em Andamento": Implementação da tela e funcionamento correto.
- Criação da página e componente "GetFichaById".
- Criação da página e componente "UpdateFicha".
=> LAPA - Ajustes na Ficha de Solicitação de Serviços

back/pom.xml, back/src/main/java/br/edu/ufape/hvu/repository/seeders/AgendamentoSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/AnimalSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/AreaSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/ConsultaSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/CronogramaSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/EspecialidadeSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/EspecieSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/EstagiarioSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/FotoSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/InstituicaoSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/MedicamentoSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/MedicoSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/OrgaoSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/RacaSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/TipoConsultaSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/TutorSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/UsuarioSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/VagaSeeder.java
Os usuários criados pelos seeders não possuem cadastro no Keycloack, logo, não é possível realizar o cadastro usando as credenciais do mesmo no momento
=> Adição de seeders no sistema

front/src/components/Footer/index.module.css, front/src/components/Header/index.module.css, front/src/components/LoginForm/index.module.css, front/src/components/TextLogin/texto_login_page.module.css
Commit solicitado por Rogerio para avaliação e orientações.
(Não é a versão final)
=> Responsividade login

back/.gitignore, back/.idea/misc.xml, back/src/main/java/br/edu/ufape/hvu/controller/FileController.java, back/src/main/java/br/edu/ufape/hvu/controller/OrgaoController.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/request/FotoRequest.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/request/LaudoNecropsiaRequest.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/request/OrgaoRequest.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/response/FotoResponse.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/response/LaudoNecropsiaResponse.java, back/src/main/java/br/edu/ufape/hvu/controller/dto/response/OrgaoResponse.java, back/src/main/java/br/edu/ufape/hvu/exception/FileException.java, back/src/main/java/br/edu/ufape/hvu/facade/Facade.java, back/src/main/java/br/edu/ufape/hvu/model/Foto.java, back/src/main/java/br/edu/ufape/hvu/model/LaudoNecropsia.java, back/src/main/java/br/edu/ufape/hvu/model/Orgao.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/FotoSeeder.java, back/src/main/java/br/edu/ufape/hvu/repository/seeders/OrgaoSeeder.java, back/src/main/java/br/edu/ufape/hvu/service/FileService.java, back/src/main/java/br/edu/ufape/hvu/service/FileServiceInterface.java, back/src/main/java/br/edu/ufape/hvu/service/FotoService.java, back/src/main/resources/application.yml
> Modificação na fachada
> Modificação do uso de imagens nas classes Orgão e Laudo Necropsia
> Implementação do upload de imagens
=> Implementações e alterações no LAPA

front/src/components/CreateMedico/index.js
Verificação de quantidade de caracteres e cpf
=> Verificação de senha em createMedico

front/pages/index.js, front/src/components/ModalAgendamento/index.js, front/src/components/ReagendarConsulta/index.js, front/src/components/ReagendarConsulta/index.module.css, front/src/components/TabelaAgendamento/index.js, front/src/components/TabelaAgendamento/index.module.css
Foi retirado o botão de reagendar em vagas que não possuem reagendamento
=> [FRONT] Listar vagas disponíveis no reagendamento

front/src/components/CreateTutorEnderecoForm/createEnderecoForm.js
Mudança solicitada, de LAI para LGPD.
=> Mudança de Lei.

back/src/main/java/br/edu/ufape/hvu/controller/AgendamentoController.java, back/src/main/java/br/edu/ufape/hvu/controller/MedicoController.java, back/src/main/java/br/edu/ufape/hvu/facade/Facade.java, back/src/main/java/br/edu/ufape/hvu/service/AgendamentoService.java, back/src/main/java/br/edu/ufape/hvu/service/AgendamentoServiceInterface.java, front/package-lock.json, front/package.json, front/services/tutorService.js
Foi identificado e corrigido automaticamente conflitos em arquivos do sistema como um todo.
=> Corrigindo conflitos e adicionando sistema de autorização de rotas

front/src/components/SystemForm/index.js, front/src/components/SystemForm/index.module.css
Fiz uma mudança para o botão não invadir o espaço do cabeçalho, mas ainda terão de ser feitas mudanças de responsividade.
=> Alteração no botão 'voltar' da tela system

front/src/components/AgendamentoEspecial/index.js
alteração na seleção de paciente para agendamento.
=> Colocando nome do tutor e parte do cpf ao lado do nome do animal.

front/src/components/GetAllMedicos/index.module.css, front/src/components/MeusAgendamentos/index.js, front/src/components/MeusAgendamentos/index.module.css, front/src/components/PacientesBySecretario/index.module.css, front/src/components/SearchBar/index.module.css
Listagem de veterinários, listagem de pacientes, caixa de confirmação de cancelamento de agendamento(tutor).
=> Responsividade de algumas telas

front/src/components/GerenciarEspecialidades/index.js, front/src/components/GerenciarEspecialidades/index.module.css, front/src/components/GerenciarEspecies/index.js, front/src/components/GerenciarEspecies/index.module.css, front/src/components/GerenciarTiposConsulta/index.js, front/src/components/GerenciarTiposConsulta/index.module.css, front/src/components/MeuPerfil/index.js, front/src/components/MeuPerfil/index.module.css
páginas: Listagem de espécies, listagem de especialidades, listagem de tipos de consulta, meu perfil.
=> Responsividade de algumas pags do secretário

front/src/components/AgendamentoEspecial/index.js
Refatorado o código para permitir que o usuário filtre animais digitando no campo de seleção,  
mantendo a estilização original e melhorando a experiência na escolha do paciente.
=> refactor(agendamento): melhorar usabilidade do select de animais

front/pages/fichaClinicaMedica/index.js
Edição no page da ficha clinica medica
=> feat(FichaClinicaMedicaPage): estruturar layout com cabeçalho e rodapé

front/src/components/Fichas/OrtopedicoStepForm/OrtopedicoHistorico/index.js, front/src/components/Fichas/OrtopedicoStepForm/OrtopedicoHistorico/index.module.css, front/src/components/Fichas/OrtopedicoStepForm/OrtopedicoMarcha/index.js, front/src/components/Fichas/OrtopedicoStepForm/OrtopedicoMarcha/index.module.css, front/src/components/Fichas/OrtopedicoStepForm/OrtopedicoPalpacao/index.js, front/src/components/Fichas/OrtopedicoStepForm/OrtopedicoPalpacao/index.module.css, front/src/components/Fichas/OrtopedicoStepForm/index.js
-foi adicionado um select para o componente 'marcha' e o CSS foi adaptado para aplicar a faixa a todos os elementos h2.
=> Adaptações da ficha ortopédica 

back/src/main/java/br/edu/ufape/hvu/controller/AreaController.java, back/src/main/java/br/edu/ufape/hvu/controller/AuthController.java, back/src/main/java/br/edu/ufape/hvu/controller/CampoLaudoMicroscopiaController.java, back/src/main/java/br/edu/ufape/hvu/controller/ConsultaController.java, back/src/main/java/br/edu/ufape/hvu/controller/CronogramaController.java, back/src/main/java/br/edu/ufape/hvu/controller/EnderecoController.java, back/src/main/java/br/edu/ufape/hvu/controller/EspecialidadeController.java, back/src/main/java/br/edu/ufape/hvu/controller/EspecieController.java, back/src/main/java/br/edu/ufape/hvu/controller/EstagiarioController.java, back/src/main/java/br/edu/ufape/hvu/controller/EtapaController.java, back/src/main/java/br/edu/ufape/hvu/controller/FichaController.java, back/src/main/java/br/edu/ufape/hvu/controller/FichaSolicitacaoServicoController.java, back/src/main/java/br/edu/ufape/hvu/controller/FileController.java, back/src/main/java/br/edu/ufape/hvu/controller/FotoController.java, back/src/main/java/br/edu/ufape/hvu/controller/InstituicaoController.java, back/src/main/java/br/edu/ufape/hvu/controller/LaudoNecropsiaController.java, back/src/main/java/br/edu/ufape/hvu/controller/MaterialColetadoController.java, back/src/main/java/br/edu/ufape/hvu/controller/OrgaoController.java, back/src/main/java/br/edu/ufape/hvu/controller/RacaController.java, back/src/main/java/br/edu/ufape/hvu/controller/VagaController.java
- Remoção de model mappers desnecessários
- Remoção de autowired
- Adição de @RequiredArgsConstructor
=> Refatorações na injeção de dependências nos controladores

back/src/main/java/br/edu/ufape/hvu/service/AgendamentoService.java, back/src/main/java/br/edu/ufape/hvu/service/AnimalService.java, back/src/main/java/br/edu/ufape/hvu/service/AreaService.java, back/src/main/java/br/edu/ufape/hvu/service/AvisoService.java, back/src/main/java/br/edu/ufape/hvu/service/CampoLaudoMicroscopiaService.java, back/src/main/java/br/edu/ufape/hvu/service/CampoLaudoService.java, back/src/main/java/br/edu/ufape/hvu/service/CancelamentoService.java, back/src/main/java/br/edu/ufape/hvu/service/ConsultaService.java, back/src/main/java/br/edu/ufape/hvu/service/CronogramaService.java, back/src/main/java/br/edu/ufape/hvu/service/EnderecoService.java, back/src/main/java/br/edu/ufape/hvu/service/EspecialidadeService.java, back/src/main/java/br/edu/ufape/hvu/service/EspecieService.java, back/src/main/java/br/edu/ufape/hvu/service/EstagiarioService.java, back/src/main/java/br/edu/ufape/hvu/service/EtapaService.java, back/src/main/java/br/edu/ufape/hvu/service/FichaService.java, back/src/main/java/br/edu/ufape/hvu/service/FichaSolicitacaoServicoService.java, back/src/main/java/br/edu/ufape/hvu/service/FotoService.java, back/src/main/java/br/edu/ufape/hvu/service/InstituicaoService.java, back/src/main/java/br/edu/ufape/hvu/service/LaudoNecropsiaService.java, back/src/main/java/br/edu/ufape/hvu/service/MaterialColetadoService.java, back/src/main/java/br/edu/ufape/hvu/service/OrgaoService.java, back/src/main/java/br/edu/ufape/hvu/service/RacaService.java, back/src/main/java/br/edu/ufape/hvu/service/VagaService.java
adição de @RequiredArgsConstructor
=> Refatoração de injeção de dependências no pacote services

front/package-lock.json, front/package.json, front/src/components/CreateConsulta/index.js, front/src/components/Fichas/Anestesiologia/PosAnestesia/index.js, front/src/components/Fichas/Anestesiologia/PosAnestesia/index.module.css
Adiciona a tabela, o gráfico e ajusta a exibição dos dados na tela inicial das fichas criadas.
=> Adicionando tabela e gráfico para a ficha de anestesiologia

front/src/components/CreateConsulta/index.js, front/src/components/Fichas/FichaSolicitacaoCitologia/index.js
- Adicionada formatação dos dados digitados pelo usuário na ficha de solicitação de exames
- Implementada renderização da imagem alterada na ficha de create consulta
=> Segunda entrega
